### ISSUE TITLE
issue with PDF

### ISSUE THREAD

**Issue by x4b1** [jsreport/jsreport-chrome-pdf#20] opened 2018-12-28 09:28 UTC
I'm trying to generate a PDF and upload to a third party, but I get an error when I download from the download button, that is like if I download from API.
<img width="1279" alt="screenshot_2018-12-28_at_10_08_47" src="https://user-images.githubusercontent.com/6052966/50510318-89310800-0a89-11e9-9679-51e199c0a782.png">

If I generate the file in jsreport previewer and I download it "printing", I works fine.
<img width="1275" alt="screenshot_2018-12-28_at_10_11_36" src="https://user-images.githubusercontent.com/6052966/50510343-a49c1300-0a89-11e9-8ccb-013138e66802.png">

Checking the differences, the first one (which fails) it is generated in 1.3 pdf version, and the one that works fine has 1.7 version

<img width="1232" alt="screenshot 2018-12-28 at 10 20 49" src="https://user-images.githubusercontent.com/6052966/50510561-808d0180-0a8a-11e9-9e1d-d7eb0307d2b1.png">

Could the version it generates be updated?

**Comment by pofider** [comment] 2018-12-28 10:40
The headless chrome we use currently produces the 1.4 pdf version.
The pdf utils you seems to be using produces the 1.3 pdf version.
The "print" feature in preview uses some kind of completely different technology. On my pc Microsoft: Print To PDF and produces 1.7.

We could update the version in pdf utils, but not sure if that will fix it for you.
What kind of thirdparty you use?
Does it help if you simply edit the version in the downloaded pdf?

**Comment by x4b1** [comment] 2018-12-28 10:55
The third party I'm using is visma sign https://vismasign.fi/ it is a platform to sign documents.
If I download the pdf and regenerated it on my pc also works.

**Comment by ealves-pt** [comment] 2019-01-02 12:44
Hey @pofider.

It would be perfect if **pdf-utils** produces 1.4 pdf version (same as chrome-pdf). It would solve our issue.

**Edit:** I will update to the latest package version to see if it solves the problem.

**Edit 2:** Updated pdf-utils to v1.2.1 and it produces 1.3 pdf version. Can you help with this one?

**Comment by pofider** [comment] 2019-01-09 23:30
Unfortunately, that tool is available in just a few countries. Or at least I am not able to register to try it.

Question. Does it help if you simply edit the version in the downloaded pdf? Using some text editor.

So the problem is the pdf utils? If you remove pdf utils and just download pdf. You get pdf 1.4. Does it work in that tool? (Don't use "print feature in preview", but download.)

**Comment by ealves-pt** [comment] 2019-01-11 09:23
The output of simply using chrome-pdf works well and we are using the API to get the output.

But if we start using pdf-utils it doesn't work anymore.

My solution was to use child templates instead of pdf-utils. This way we can achieve the same output but I must confess that it is not my preferred solution.

**Comment by pofider** [comment] 2019-01-14 15:02
> The output of simply using chrome-pdf works well and we are using the API to get the output.

Ok. Thanks. I created a more relevant issue for us here
https://github.com/jsreport/jsreport-pdf-utils/issues/14

> My solution was to use child templates instead of pdf-utils. This way we can achieve the same output but I must confess that it is not my preferred solution.

Thinking now what you are actually trying to reach with pdf utils.
Because child templates and pdf utils are solving different problems.
If the assets/child templates are able to solve your problem. It is a probably better idea to use them instead of the pdf utils.

**Comment by ealves-pt** [comment] 2019-01-14 15:07
Yes for now it solves our problem and we are happy with it.

Feel free to close this ticket in favor of the one you just created.

Thanks for the help.

**Comment by pofider** [comment] 2019-01-14 15:19
Ok. Thanks for the info. Closing in favour of jsreport/jsreport-pdf-utils#14

**Closed as completed by pofider** 2019-01-14 15:19 UTC
