### ISSUE TITLE
Landscape mode - width, height do not work

### ISSUE THREAD

**Issue by NameGrey** [jsreport/jsreport-chrome-pdf#28] opened 2022-08-05 11:31 UTC
Hi everyone.

I have html page with fixed size width: 842px, height: 595px. I am trying to build a pdf report for that page, however the page is just part of the final report (see picture below)
![image](https://user-images.githubusercontent.com/6246048/183067980-2396b6b2-ed12-4a34-ae80-f2c8438a825d.png)

Blue background is my page I expect being full sized.

Here is an example I have created (width and height do not work and do nothing when I change them):

https://playground.jsreport.net/w/NameGrey/BspPcQG7

Additionally I tried to use "scale". And set it to "1.5" or "1.33333333" or any similar value, but in that case I could see an additional 1px white line in the bottom and right borders.

![image](https://user-images.githubusercontent.com/6246048/183068487-f5a168d7-7fa9-4d41-9dc5-50678faab671.png)

Please assist me with that problem.

**Comment by pofider** [comment] 2022-08-05 14:00
Duplicate of https://github.com/jsreport/jsreport/issues/948

**Closed as completed by pofider** 2022-08-05 14:00 UTC
